# Пожалуйста не изменяйте версию конфига если вы не знаете что делаете!
config_version = 16
uuidupdated = true
region_negative_min_max_updated = true

# ---------------------------------------------------------------------------------------
# Конфиг ProtectionStones
# Конфиги блоков были перемещены в папку blocks.
# Чтобы создать новые блоки, скопируйте файл по умолчанию "block1.toml" и создайте другой файл (например, "block2.toml").
# Ваш конфиг выглядит беспорядочным? Возможно, это из-за постепенного обновления конфигурации. Рассмотрите возможность использования конфигураций по умолчанию.
# Если вам снова понадобятся конфигурации по умолчанию, вы можете получить их отсюда: https://github.com/espidev/ProtectionStones/tree/master/src/main/resources.
# ---------------------------------------------------------------------------------------

# Время ожидания между установкой блоков защиты (в секундах). -1 для отключения.
placing_cooldown = -1

# Установите значение true, чтобы не блокировать запуск сервера для загрузки кэша UUID.
# /ps add и /ps remove не будут работать для автономных игроков до тех пор, пока загрузка кэша не будет завершена.
async_load_uuid_cache = false

# Разрешать или нет регионам иметь одинаковые имена (из /ps name).
# Если установлено значение true, игрокам придется использовать цифры после имени, если они столкнутся с дубликатами.
allow_duplicate_region_names = false

# Время в секундах между /ps view attempts.
# Может предотвратить лаги из-за спама командой.
ps_view_cooldown = 3

# Базовая команда для ProtectionStones (измените, если она конфликтует с другими командами)
base_command = "ps"

# Алиасы для команд. По ним можно будет так же обратиться к плагину
aliases = [
    "pstone",
    "protectionstone",
    "protectionstones"
]

# Следует ли сбрасывать предметы на землю, если инвентарь переполнен (например, во время /ps unclaim).
# Если установлено значение false, событие не произойдет, и будет сказано, что инвентарь полон.
drop_item_when_inventory_full = true

# Должны ли размещаемые регионы быть либо рядом, либо перекрывать существующие регионы, которыми игрок уже владеет.
# Это может сделать мир чище и уменьшить разбросанность регионов.
# Установите количество несмежных регионов с разрешением protectionstones.adjacent.x (по умолчанию 1, -1 для обхода)
# Вы можете обойти это ограничение при помощи права protectionstones.admin
regions_must_be_adjacent = false

# Давать ли игрокам возможность объединять новые регионы с теми, которыми они уже владеют (перекрытие).
# для создания нового большого региона. Можно объединить любые регионы с помощью protectionstones.admin
# Требуется разрешение protectionstones.merge для использования (для команды /ps merge)
# ПРИМЕЧАНИЕ: Из-за ограничений WorldGuard, объединенные регионы будут игнорировать y_radius и идти от бедрока к небу.
# поскольку полигональные области могут быть только 2D, а не 3D
allow_merging_regions = true

# Разрешать или нет объединенным регионам иметь отверстия в них (объединение кучи регионов в круг, внутренняя часть которого не защищена).
# Это проверяется только во время процесса слияния, он не будет удалять регионы с уже имеющимися отверстиями.
allow_merging_holes = true

# Выключено ли у игроков по умолчанию размещение блоков защиты (эквивалентно выполнению /ps toggle).
default_protection_block_placement_off = false

# Если у вас нет LuckPerms, ProtectionStones не может определить пределы оффлайн игроков (так как это зависит от
# от разрешений), и поэтому он требует, чтобы игроки были онлайн. Установите значение true, если вашему серверу не нужны лимиты (и поэтому
# проверка не нужна).
allow_addowner_for_offline_players_without_lp = false

# Могут ли члены региона возвращаться домой в регион по команде /ps home
allow_home_teleport_for_members = true

[admin]
    # Должен ли "/ps admin cleanup remove" удалять регионы, которые имеют членов, но не имеют владельцев (после того, как неактивные
    # владельцы удаляются).
    # Регионы, у которых нет владельцев или членов, будут удалены независимо от этого.
    cleanup_delete_regions_with_members_but_no_owners = true

[economy]
    # Устанавливает ограничения на цену аренды. Установите значение -1.0, чтобы отключить.
    max_rent_price = -1.0
    min_rent_price = 1.0

    # Установка ограничений на период между арендными платежами в секундах (86400 секунд = 1 день). Установите значение -1, чтобы отключить.
    max_rent_period = -1
    min_rent_period = 1

    # Установите налоги для регионов.
    # Налоги настраиваются в конфигурации каждого отдельного блока.
    # Включать или не включать команду налогов.
    # Если у вас уже есть регионы, вы можете установить в каждом из них автоплательщика (игрока, который автоматически платит налоги).
    # Это можно сделать с помощью команды /ps admin settaxautopayers, которая обновляет каждый регион на сервере с автоплательщиком из списка его владельцев.
    tax_enabled = false

    # Уведомлять игроков о неоплаченных налоговых платежах за регионы, которыми они владеют.
    tax_message_on_join = true
