Title: '#5d6d7e           &lНастройки'
Size: 45

Content:
  return:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmU5YWU3YTRiZTY1ZmNiYWVlNjUxODEzODlhMmY3ZDQ3ZTJlMzI2ZGI1OWVhM2ViNzg5YTkyYzg1ZWE0NiJ9fX0=
      Name: '#e3fbf9(↓) &lНазад'
    Slots: 40
    Type: RETURN
    Priority: 5

Editor:
  location:
    Item:
      Material: COMPASS
      Name: '#ee9aff&lЛокация'
      Lore:
      - '#ee9aff▪ #ddeceeМир: #ee9aff%home_location_world%'
      - '#ee9aff▪ #ddeceeX: #ee9aff%home_location_x%'
      - '#ee9aff▪ #ddeceeY: #ee9aff%home_location_y%'
      - '#ee9aff▪ #ddeceeZ: #ee9aff%home_location_z%'
      - ''
      - '#9af7ff&lДействие:'
      - '#9af7ff▪ #ddeceeЛКМ: #9af7ffУстановить текущие координаты'
    Slots: 4
    Type: HOME_CHANGE_LOCATION
    Priority: 5
  
  def:
    Item:
      Material: GREEN_BED
      Name: '#ee9aff&lТочка дома по умолчанию'
      Lore:
      - '#ee9aff▪ #ddeceeВключено: #ee9aff%home_is_default%'
      - ''
      - '#ddeceeПри активации телепортирует вас в этот дом.'
      - '#ddeceeВам нет необходимости прописывать название точки дома.'
      - ''
      - '#9af7ff&lДействие:'
      - '#9af7ff▪ #ddeceeЛКМ: #9af7ffВкл/Выкл'
    Slots: 19
    Type: HOME_CHANGE_DEFAULT
    Priority: 5
  
  respawn:
    Item:
      Material: RED_BED
      Name: '#ee9aff&lВозрождение после смерти'
      Lore:
      - '#ee9aff▪ #ddeceeВключено: #ee9aff%home_is_respawn_point%'
      - ''
      - '#ddeceeПри включении телепортирует вас в этот дом'
      - '#ddeceeпри возрождении после смерти.'
      - ''
      - '#9af7ff&lДействие:'
      - '#9af7ff▪ #ddeceeЛКМ: #9af7ffВкл/Выкл'
    Slots: 20
    Type: HOME_CHANGE_RESPAWN_POINT
    Priority: 5
  
  name:
    Item:
      Material: NAME_TAG
      Name: '#ee9aff&lОтображаемое имя'
      Lore:
      - '#ee9aff▪ #ddeceeТекущее: #ee9aff%home_name%'
      - ''
      - '#ddeceeУстанавливает отображаемое имя дома.'
      - '#ddeceeБудет отображаться в меню и сообщениях.'
      - ''
      - '#9af7ff&lДействие:'
      - '#9af7ff▪ #ddeceeЛКМ: #9af7ffИзменить'
    Slots: 21
    Type: HOME_CHANGE_NAME
    Priority: 5
  
  public:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2I1NmU0OTA4NWY1NWQ1ZGUyMTVhZmQyNmZjNGYxYWZlOWMzNDMxM2VmZjk4ZTNlNTgyNDVkZWYwNmU1ODU4YyJ9fX0=
      Name: '#ee9aff&lТип дома'
      Lore:
      - '#ee9aff▪ #ddeceeТекущий: #ee9aff%home_type%'
      - ''
      - '#ddeceeОбщий дом позволяет любому игроку посетить его.'
      - '#ddeceeПриватный дом доступен только по приглашениям.'
      - ''
      - '#9af7ff&lДействие:'
      - '#9af7ff▪ #ddeceeЛКМ: #9af7ffВкл/Выкл'
    Slots: 22
    Type: HOME_CHANGE_TYPE
    Priority: 5
  
  icon:
    Item:
      Material: ITEM_FRAME
      Name: '#ee9aff&lЗначок'
      Lore:
      - '#ddeceeУстанавливает значок дома,'
      - '#ddeceeкоторый будет отображаться в графическом интерфейсе.'
      - ''
      - '#9af7ff&lДействие:'
      - '#9af7ff▪ #ddeceeПоместить предмет: #9af7ffИзменить'
    Slots: 23
    Type: HOME_CHANGE_ICON
    Priority: 5
  
  invites:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTc5ZTkxMTczY2U1NzhlMWI1NWYyMGYxMTk2NjE3NDI5ZWE2ODhlNjczNDVkN2ZmYmNmNWFhZWRkNjViZjU5OSJ9fX0=
      Name: '#ee9aff&lПриглашенные игроки'
      Lore:
      - '#ee9aff▪ #ddeceeПриглашены: #ee9aff%home_invited_players%'
      - ''
      - '#ddeceeСписок игроков, которые могут посетить'
      - '#ddeceeтвой дом в любое время.'
      - ''
      - '#9af7ff&lДействие:'
      - '#9af7ff▪ #ddeceeЛКМ: #9af7ffДобавить игроков'
      - '#9af7ff▪ #ddeceeПКМ: #9af7ffОчистить список'
    Slots: 24
    Type: HOME_CHANGE_INVITED_PLAYERS
    Priority: 5
# Sets Inventory Type for the GUI.
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/inventory/InventoryType.html
Inventory_Type: CHEST
# Sets whether to use Paper's MiniMessage API for the GUI Title.
Use_Mini_Message: false
