# Define your protection block below
# Use block type from here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# --------------------------------------------------------------------------------------------------
# Если вы хотите использовать головы игроков, вы можете использовать "PLAYER_HEAD:имя_игрока" (например, "PLAYER_HEAD:Notch").
# Чтобы использовать пользовательские головы игроков, вам нужно значение base64 головы. На сайте minecraft-heads.com вы найдете это значение в разделе "Другое" под "Value:".
# Чтобы использовать UUID для голов игроков, перейдите на сайт https://sessionserver.mojang.com/session/minecraft/profile/PUT-UUID-HERE и скопируйте значение из поля "value", не включая кавычки.
# Когда у вас есть значение, вы можете установить тип "PLAYER_HEAD:значение".
type = "EMERALD_ORE"

# Еще один способ сослаться на Protection Stones.
# Может использоваться для /ps give и /ps get
# Должно быть одно слово (без пробелов)
alias = "64"

# Описание типа блока защиты
# Отображается в меню /ps get
description = "Защитная зона радиусом 64 блока."

# Ограничивать ли получение защитного камня только /ps get и /ps give и пользовательскими рецептами ремесла.
# Другие способы получения этого блока (например, добыча полезных ископаемых) не будут работать в качестве защитного камня.
# Полезно разрешить получение защитного блока только из магазина или команды.
# Установите значение "false", если вы хотите разрешить игрокам получать защитный камень естественным путем.
restrict_obtaining = true

# Включите или отключите использование этого защитного камня в определенных мирах.
# режим "blacklist" предотвращает использование этого защитного блока в мирах в "мирах".
# Режим "whitelist" позволяет использовать этот защитный блок только в мирах в "мирах".
# Может быть отменен с правами protectionstones.admin (включая OP)!
world_list_type = "blacklist"
worlds = [
    "exampleworld1",
    "exampleworld2"
]

# Следует ли на самом деле ограничивать размещение защитного камня, когда мир ограничен (blacklist/whitelist)
# Блок разместится нормально, без поведения PS.
prevent_block_place_in_restricted_world = true

# Разрешить или не разрешить размещение блока в дикой природе.
# Если установлено значение false, защитный блок может быть размещен только в существующих регионах.
allow_placing_in_wild = true

# Разрешить или нет блоку обходить флаг прохода WorldGuard.
# Это позволяет разместить защитный блок, даже если WorldGuard запрещает размещение блока в дикой природе.
placing_bypasses_wg_passthrough = true

[region]
# Минимальное расстояние между заявками (которые не принадлежат одному владельцу), измеренное от блока защиты до границы другого региона
    # Вам, вероятно, придется изменять это между блоками, так как размеры областей будут разными
    # Установите значение -1 для отсутствия минимума, но все равно будете проверять наличие перекрывающихся областей
    distance_between_claims = -1

    # Радиус защиты блока (радиус 64 -> область 129 x 129)
    # Установите y_radius равным -1, если вы хотите, чтобы он защищал для всех уровней y.
    # y_radius должен быть равен -1, если вы разрешаете объединение региона (опция "allow_merging")
    x_radius = 64
    y_radius = -1
    z_radius = 64

    # Включает "режим привязки к чанкам", при котором границы региона будут определяться чанком, в котором находится блок, и параметром
    # chunk_radius (на сколько чанков отстоит от центрального чанка).
    # Позволяет игрокам не беспокоиться о точном размещении своего блока и устраняет проблему беспорядочного перекрытия
    # регионов (так как все они соответствуют границам чанков).
    # Установите значение -1, чтобы отключить, и любое число больше или равно 1, чтобы включить.
    # Примечание: Если включено, x_radius и z_radius будут игнорироваться!
    chunk_radius = -1

    # На сколько блоков нужно сместить стандартное расположение /ps home от блока защиты
    home_x_offset = 0.0
    home_y_offset = 1.0
    home_z_offset = 0.0

    # Укажите флаги по умолчанию, которые будут установлены при создании нового защищенного региона.
    # Можно использовать -g [group] перед флагом для установки групповых флагов (например, -g members pvp deny).
    # Можно использовать PlaceholderAPI в строковых флагах (например, приветствие, прощание).
    flags = [
        "pvp deny",
        "tnt deny",
        "greeting &lEntering &b&l%player%'s &f&lprotected area",
        "farewell &lLeaving &b&l%player%'s &f&lprotected area",
        "greeting-action &lEntering &b&l%player%'s &f&lprotected area",
        "farewell-action &lLeaving &b&l%player%'s &f&lprotected area",
        "creeper-explosion deny",
        "wither-damage deny",
        "ghast-fireball deny",
    ]

    # Перечислите все флаги, которые могут быть установлены владельцами регионов.
    # Если вы хотите составить белый список групп, которые также могут быть установлены, используйте -g (например, "-g all,members pvp" ограничивает его отсутствием флага группы и группой членов)
    # "-g all pvp" - предотвращает установку игроками группы, не являющейся членом, и неуязвимости для атак.
    allowed_flags = [
        "-g all pvp",
        "greeting",
        "greeting-title",
        "greeting-action",
        "farewell",
        "farewell-title",
        "farewell-action",
        "mob-spawning",
        "creeper-explosion",
        "wither-damage",
        "ghast-fireball",
    ]

    # Какие флаги скрывать от /ps info
    hidden_flags_from_info = [
        "ps-name",
        "ps-merged-regions",
        "ps-merged-regions-types",
        "ps-block-material",
        "ps-price",
        "ps-landlord",
        "ps-tenant",
        "ps-rent-period",
        "ps-rent-last-paid",
        "ps-for-sale",
        "ps-rent-settings",
        "ps-tax-payments-due",
        "ps-tax-last-payment-added",
        "ps-tax-autopayer"
    ]

    # Тип приоритета по умолчанию для этого блока тип Protection Stone
    priority = 0

    # Разрешать или нет создание регионов, перекрывающих другие регионы, которые вам не принадлежат.
    # Это опасно, так что подумайте об этом тщательно, если вы установите значение true.
    allow_overlap_unowned_regions = false

    # Разрешать или нет игрокам создавать другие регионы, которые перекрывают этот регион.
    # "owner" - разрешить только владельцам перекрывать этот регион (по умолчанию).
    # "member" - разрешить членам и владельцам перекрывать этот тип региона. (полезно для городских участков)
    # "all" - разрешить всем игрокам перекрывать этот тип региона.
    # "none" - ни один игрок, даже владельцы региона не могут перекрывать его.
    # allow_overlap_unowned_regions не обязательно должно быть true, чтобы это работало.
    allow_other_regions_to_overlap = "owner"

    # Разрешать или нет регионам, созданным с помощью этого блока, объединяться с другими регионами.
    # allow_merging_regions должно быть установлено в true в config.toml
    allow_merging = true

    # Разрешенные типы регионов для слияния (обозначаются псевдонимом)
    # Обязательно добавьте псевдоним текущего типа региона, чтобы разрешить слияние с ним, например. ["64"]
    # Добавьте "all", если вы хотите разрешить этому региону сливаться с любым регионом.
    allowed_merging_into_types = [
        "all"
    ]

[block_data]
    # Имя, даваемое блоку защиты при получении с помощью /ps give или /ps get.
    # Также влияет на созданные предметы (см. custom_recipe)
    # Оставить как '' для отсутствия имени
    display_name = "&a&m<---&r&b Защитная зона радиусом 64 блока &r&a&m--->"

    # Описание дается блоку защиты, когда он получен с помощью /ps give или /ps get
    # Также влияет на созданные предметы (см. custom_recipe)
    # Оставьте значение [], чтобы не было никакого описания
    lore = [
        "&6(⌐■_■)ノ♪ Никто не тронет мои вещи!",
    ]

    # Должен ли предмет иметь эффект "свечения/зачарования", когда он находится в инвентаре игрока.
    enchanted_effect = false

    # Добавить цену при использовании /ps get
    # Должен иметь совместимый плагин экономики (требует Vault, т.е. Essentials)
    # Должна быть десятичной дробью (например, не 10, а 10.0)
    price = 0.0

    # Разрешить или нет создание этого предмета с помощью пользовательского рецепта.
    # Полезно разрешить крафтинг предмета, когда restrict_obtaining установлен в true
    allow_craft_with_custom_recipe = true
    # Укажите пользовательский рецепт крафтинга ниже
    # Вы должны заполнить места предметов названиями отсюда: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    # Вы также можете использовать другие protection stones в качестве ингредиентов в рецепте, в формате PROTECTION_STONES:alias.
    # Убедитесь, что вы установили allow_use_in_crafting для этого блока в true, иначе вы не сможете использовать его в крафтинге.
    # Если вам нужен воздух, вы можете просто оставить место как "".
    custom_recipe = [
        ["", "STONE", ""],
        ["STONE", "EMERALD", "STONE"],
        ["", "STONE", ""]
    ]
    # Количество блока(ов) защиты, который нужно предоставить при создании
    recipe_amount = 1

    # Данные пользовательской модели элемента блока, полезные для пакетов ресурсов. Установите значение -1 для отключения.
    custom_model_data = -1

[economy]
    # Сначала налоги должны быть включены в config.toml (tax_enabled)
    # Сумма налога для региона за налоговый цикл.
    # Должна быть десятичной дробью (например, не 10, а 10.0)
    tax_amount = 0.0

    # Количество секунд между циклами налогов. Установите значение -1, чтобы отключить налоги.
    tax_period = -1

    # Количество времени для уплаты налогов в секундах после налогового цикла до наступления наказания.
    tax_payment_time = 86400

    # Автоматически установите игрока, создавшего регион, в качестве налогоплательщика.
    start_with_tax_autopay = true

    # В какой роли должны быть добавлены арендаторы (для аренды). Это может быть либо "owner", либо "member".
    tenant_rent_role = "member"

    # Должны ли арендодатели сдаваемых в аренду регионов оставаться собственниками, пока регионы сдаются в аренду?
    landlord_still_owner = false

[behaviour]
   # Спрятать защитный камень сразу после размещения?
    auto_hide = false

    # Следует ли автоматически сливаться с другими регионами при размещении, если есть только один перекрывающийся регион и allow_merging равно true
    auto_merge = false

    # Отключить возврат блока, когда он удален/невостребован?
    no_drop = false

    # Предотвращает выталкивание поршня из блока. Рекомендуется держать как истинный.
    prevent_piston_push = true

    # Предотвращает разрушение блока при взрыве.
    # Рекомендуется держать true, чтобы игроки не могли использовать больше камней защиты с помощью /ps unhide (когда блок разрушен).
    prevent_explode = true

    # Разрушает область защитного камня при взрыве блока. Может быть полезно для PVP/Factions серверов.
    # prevent_explode должно быть false, чтобы это работало.
    destroy_region_when_explode = false

    # Silk Touch: если true, рудные блоки, которые также сконфигурированы камнями защиты, будут запрещать капли Silk Touch.
    # Это было старое поведение для предотвращения естественного получения камня защиты.
    # Рекомендуется оставить false, если "Ограничить получение" (новый способ) истинен.
    prevent_silk_touch = false

    # Установить стоимость размещения блока защиты (отдельно от /ps get cost)
    cost_to_place = 0.0

    # Разрешить выплавлять в печах элементы защитного блока
    allow_smelt_item = false

    # Позволяет использовать блок защиты в рецептах крафтинга.
    # Вы можете установить значение false, чтобы игроки не разлагали его элементы.
    allow_use_in_crafting = false

[player]
    # Разрешать или нет разрушение блока защиты нажатием shift-right.
    # Полезно, если защитный блок является неразрушимым (камень, командный блок) и т.д.
    allow_shift_right_break = false

    # Предотвращать или нет телепортацию в защищенный регион, если игрок не владеет им (кроме жемчужины эндера и фрукта хоруса).
    # Не предотвращает вход, для предотвращения входа используйте флаг "entry deny".
    # Обход с помощью protectionstones.tp.bypassprevent
    prevent_teleport_in = false

    # Невозможно двигаться в течение x секунд перед телепортацией с помощью /ps home или /ps tp. Можно отключить с помощью 0.
    # Опция телепортироваться, только если игрок стоит на месте.
    # Можно переопределить с помощью разрешения protectionstones.tp.bypasswait
    no_moving_when_tp_waiting = true
    tp_waiting_seconds = 0

    # Нужно ли запретить получение этого блока через /ps get.
    # Игнорируется при использовании protectionstones.admin
    prevent_ps_get = false

    # Следует ли запретить этому типу региона отображаться в /ps home и разрешить телепорт.
    # Примечание: администраторы все еще могут использовать /ps tp для этого типа региона.
    prevent_ps_home = false

    # Требуется дополнительное разрешение для размещения этого конкретного блока защиты (вам все еще нужен protectionstones.create)
    # Также применяется к /ps get (вам все еще нужно protectionstones.get)
    # '' для отсутствия дополнительного разрешения
    permission = ''

[event]

    # Раздел "События"
    # ~~~~~~~~~~~~~~
    # Для каждой строки о событиях - формат 'type: action'.
    # Ниже перечислены принятые типы:
    # player_command - Выполнить команду игрока, вызвавшую событие (не будет выполняться, если не применимо)
    # console_command - Выполнение команды консолью.
    # message - Отправить сообщение игроку или консоли, если применимо (поддержка цвета с помощью &)
    # global_message - Отправить сообщение всем игрокам и консоли (поддержка цвета с &)
    # console_message - Отправить сообщение на консоль (поддержка цвета с &)
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Включать или нет отслеживание событий (события API все равно будут включены)
    enable = false

    # Выполнение команд при создании региона (например, игрок ставит защитный блок)
    # Переменные: %player%, %world%, %region%, %block_x%, %block_y%, %block_z%.
    on_region_create = [
        'global_message: &l%player% создал регион %region%!',
    ]

    # Выполнение команд при уничтожении региона (например, когда игрок уничтожает блок защиты).
    # Переменные: %player%, %world%, %region%, %block_x%, %block_y%, %block_z%.
    on_region_destroy = [
        'console_command: say %player% разрушил регион %region%!',
    ]
