# __________ __                           __________       __        __
# \______   \  | _____  ___ __  __________\______   \____ |__| _____/  |_  ______
#  |     ___/  | \__  \<   |  |/ __ \_  __ \     ___/  _ \|  |/    \   __\/  ___/
#  |    |   |  |__/ __ \\___  \  ___/|  | \/    |  (  <_> )  |   |  \  |  \___ \
#  |____|   |____(____  / ____|\___  >__|  |____|   \____/|__|___|  /__| /____  >
#                     \/\/         \/                             \/          \/

# Это локаль используемая из папки /locale
# По дефолту: en_US
locale: ru_RU

# Должны ли мы зарегистрировать  в Vault в качестве плагина управляющего валютой?
# По дефолту: false
vault: false

# Уровень приоритета, который будет использоваться для Vault hook.
# Более высокие приоритеты позволят PlayerPoints загружаться раньше других экономических плагинов.
# Допустимые значения: [Lowest, Low, Normal, High, Highest].
# По дефолту: Low
vault-priority: Low

# Должны ли мы зарегистрироваться в Treasury в качестве плагина управляющего валютой?
# По дефолту: false
treasury: false

# Уровень приоритета, который будет использоваться для Treasury hook.
# Более высокие приоритеты позволят PlayerPoints загружаться раньше других экономических плагинов.
# Допустимые значения: [LOW, NORMAL, HIGH]
# По дефолту: LOW
treasury-priority: LOW

# Какое количество игроков, будет отображаться на одной странице в таблице лидеров?
# По дефолту: 10
leaderboard-per-page: 10

# Количество секунд, в течение которых баланс игрока будет храниться в кэше, прежде чем будут освобождены.
# По дефолту: 30
cache-duration: 30

# Должны ли мы отправлять обновления на другие серверы, когда значение очков игрока изменяется?
# Это должно работать для любого типа прокси.
# По дефолту: true
bungeecord-send-updates: true

# Количество записей, которые будут обновляться в таблице лидеров.
# Одновременно может быть доступно только определенное количество записей в таблице лидеров.
# При доступе к несуществующей записи вместо нее будет выводиться сообщение с заголовком.
# По умолчанию: 10
leaderboard-placeholder-entries: 10

# Количество секунд между обновлениями плейсхолдера таблицы лидеров.
# По умолчанию: 15
leaderboard-placeholder-refresh-interval: 15

# Баланс койнов, с которыми будут начинать новые игроки
# По умолчанию: 0
starting-balance: 0

# Настройки хука для голосования
vote:

  # Активны ли голосования
  # По умолчанию: false
  enabled: false

  # Сколько койнов должно быть начислено за голос
  # По умолчанию: 100
  amount: 100

  # Должны ли койны начисляться только тогда, когда проголосовавший игрок находится в сети?
  # По умолчанию: false
  online: false

# На какую команду следует перенаправить при использовании '/points' без указания подкоманды?
# Вы можете использовать здесь значение, такое как 'me', чтобы показать вывод '/points me'
# Если у вас есть определенные псевдонимы, не используйте их здесь
# Если оставить пустым, будет использовано поведение по умолчанию, отображающее версию «/points» с пропущенными разрешениями.
# По умолчанию:
base-command-redirect: ''

# Вы обновляете более старую версию PlayerPoints?
# Если вы ранее делали что-то особенное с настройками базы данных, вам может понадобиться это
# ПРЕДУПРЕЖДЕНИЕ: этот параметр может быть удален в будущем. Попробуйте обновить базу данных, чтобы использовать новый формат!legacy-database-mode:

  # Должны ли мы использовать устаревший режим базы данных?
  # По умолчанию: false
  enabled: false

  # Имя устаревшей таблицы базы данных
  # По умолчанию: playerpoints
  table-name: playerpoints

# Настройки, если вы хотите использовать MySQL для управления данными
mysql-settings:

  # Активация MySQL
  # Если false, вместо этого будет использоваться SQLite.
  # По умолчанию: false
  enabled: false

  # MySQL Имя хоста базы данных
  # Default: 
  hostname: ''

  # MySQL порт базы данных
  # Default: 3306
  port: 3306

  # MySQL имя базы данных
  # Default: 
  database-name: ''

  # MySQL имя пользователя базы данных
  # Default: 
  user-name: ''

  # MySQL пароль от пользователя
  # Default: 
  user-password: ''

  # Если соединение с базой данных должно использовать SSL
  # Вы должны включить это, если ваша база данных поддерживает SSL
  # По умолчанию: false
  use-ssl: false

  # Количество подключений к базе данных
  # По умолчанию: 3
  connection-pool-size: 3

# Это все! Вы достигли конца конфигурации.
# Наслаждайтесь плагином!