Title: '&nМеню контейнеров'
Size: 36

Crates:
  virtual:
    Display:
      default:
        Item:
          Material: PLAYER_HEAD
          Head_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDI0ODZmMjg1OTE2OWM4YmZiNjZhNjg3YmNmNGM2OTkzNDE3ZjU4NGI1OGJiZmRiMzM2NDY0ZDUyMDcxY2NkNyJ9fX0=
          Name: '%crate_name%'
          Lore:
            - '%crate_item_lore%'
            - '&7'
            - '&9▸ &7У вас есть: &9%user_keys% ключ(ей)'
            - '&9▸ &7Стоимость (монеты): &9$%crate_opening_cost_money%'
            - '&9▸ &7Стоимость (опыт): &9%crate_opening_cost_exp%'
            - '&7'
            - '&fЛКМ &7Для предпросмотра'
            - '&fПКМ &7Для открытия'
    Slots: 13

Content:
  exit:
    Display:
      default:
        Item:
          Material: 'BARRIER'
          Name: '&c&lЗакрыть'
    Slots: 31
    Type: CLOSE

  info:
    Display:
      default:
        Item:
          Material: 'BOOK'
          Name: '&e&nЧто это?'
          Lore:
            - '&6Это специальное меню контейнеров,'
            - '&6где вы можете открывать контейнеры с помощью'
            - '&6виртуальных ключей, которые вы можете купить'
            - '&6в нашем магазине.'
    Slots: 28
    Type: NONE

  store:
    Display:
      default:
        Item:
          Material: 'EMERALD'
          Name: '&a&nМагазин'
          Lore:
            - '&dКупите ключи от контейнеров в нашем магазине'
            - '&dпосле используйте их в этом меню!'
            - '&7'
            - '&bНаш магазин: &awww.store.mycraft.com'
    Slots: 34
    Type: NONE
