Title: '   &nПредпросмотр контейнера'
Size: 36

Reward:
  Hide_Drained_Rewards: false
  Name: '&e%reward_preview_name%'
  Lore:
    Default:
      - '&e&lШанс выйгрыша: &6%reward_chance%%'
      - '&e&lЛимит выйгрышей: &6%reward_win_limit_amount%'
      - '&e&lКулдаун на выйгрыш: &6%reward_win_limit_cooldown%'
      - ''
      - '%win_limit_amount%'
      - '%win_limit_cooldown%'
      - '%win_limit_drained%'
      - ''
      - '%reward_preview_lore%'
    Win_Limit:
      Amount:
        - '&7Вы можете выиграть эту награду ещё &6%user_reward_win_limit_amount_left% раз &7(от общего числа &f%reward_win_limit_amount%&7)'
      Cooldown:
        - '&7Вы можете снова выиграть эту награду в &6%user_reward_win_limit_expire_in%'
      Drained:
        - '&cВы уже выиграли эту награду, вы не можете выиграть её больше.'
  Slots: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26

Content:
  page_next:
    Display:
      default:
        Item:
          Material: ARROW
          Name: '&e&lСледующая страница'
    Slots: 35
    Type: PAGE_NEXT

  page_prev:
    Display:
      default:
        Item:
          Material: ARROW
          Name: '&e&lПредыдущая страница'
    Slots: '27'
    Type: PAGE_PREVIOUS

  exit:
    Display:
      default:
        Item:
          Material: BARRIER
          Name: '&c&lЗакрыть'
    Slots: 31
    Type: CLOSE
